server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fruitShop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:8989}
  realm: ${KEYCLOAK_REALM:fruit-shop}
  client-id: ${KEYCLOAK_CLIENT_ID:fruit-shop-client}
  username: ${KEYCLOAK_ADMIN_USERNAME:nhathn}
  password: ${KEYCLOAK_ADMIN_PASSWORD:123456}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:gIu4RyBjwS5eREaMWJHoTehs2ZH372Bi}
  scope: ${KEYCLOAK_SCOPE:openid}

default-password: Abc@123